import Foundation

// Writes the built-in rule files as Swift source for SpaceKitCore (run by the EmbedRules build plugin).
//
//   RuleEmbedder <rules folder> <output.swift> <relative path>...
//
// The text is embedded as is; whether it parses and validates is checked by SpaceKitCore's tests, which have the
// rule parser. A file that can't be read fails the build.

let arguments = CommandLine.arguments.dropFirst()
guard arguments.count >= 2 else {
    FileHandle.standardError.write(Data("usage: RuleEmbedder <rules folder> <output.swift> <relative path>...\n".utf8))
    exit(2)
}
let root = arguments[arguments.startIndex]
let output = arguments[arguments.startIndex + 1]
let names = arguments.dropFirst(2)

/// A Swift string literal holding `text` exactly.
func literal(_ text: String) -> String {
    var escaped = "\""
    for scalar in text.unicodeScalars {
        switch scalar {
        case "\\": escaped += "\\\\"
        case "\"": escaped += "\\\""
        case "\n": escaped += "\\n"
        case "\r": escaped += "\\r"
        case "\t": escaped += "\\t"
        case _ where scalar.value < 0x20 || scalar.value == 0x7F:
            escaped += "\\u{\(String(scalar.value, radix: 16))}"
        default: escaped.unicodeScalars.append(scalar)
        }
    }
    return escaped + "\""
}

var source = """
    // Generated by the EmbedRules build plugin from the repository's rules/ folder. Don't edit; edit rules/ instead.

    enum EmbeddedRuleFiles {
        static let all: [(path: String, yaml: String)] = [

    """
for name in names {
    let text: String
    do {
        text = try String(contentsOfFile: root + "/" + name, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(Data("error: can't read rules/\(name): \(error.localizedDescription)\n".utf8))
        exit(1)
    }
    source += "        (path: \(literal(name)), yaml: \(literal(text))),\n"
}
source += "    ]\n}\n"

do {
    try source.write(toFile: output, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data("error: can't write \(output): \(error.localizedDescription)\n".utf8))
    exit(1)
}
